# .gitpod.yml
image:
  file: .gitpod.Dockerfile

tasks:
  - init: ./mvnw clean install
    command: ./mvnw test

ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - testng.testng-vscode

# Example Dockerfile for Gitpod
# .gitpod.Dockerfile
FROM gitpod/workspace-full:latest

# Install Java 11
RUN sudo apt-get update && sudo apt-get install -y openjdk-11-jdk

# Install Maven
RUN sudo apt-get install -y maven

# Set JAVA_HOME environment variable
ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64
ENV PATH $JAVA_HOME/bin:$PATH

# Install Selenium WebDriver
RUN wget -q -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/91.0.4472.101/chromedriver_linux64.zip && \
    sudo unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/ && \
    rm /tmp/chromedriver.zip

# Install Chrome Browser
RUN sudo apt-get install -y google-chrome-stable
